# https://github.com/iterative/cml
name: model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py
          
          cat data_info.txt >> report.md
          cat metrics.txt >> report.md

          cml-publish performance_training.png --md >> report.md
          cml-publish performance_test.png --md >> report.md
          cml-publish feature_importance.png --md >> report.md
          echo "high_mean_errors" >> report.md
          cml-publish high_mean_errors.png --md >> report.md
          echo "low_mean_errors" >> report.md
          cml-publish low_mean_errors.png --md >> report.md
          echo "high_std_errors" >> report.md
          cml-publish high_std_errors.png --md >> report.md
          echo "low_std_errors" >> report.md
          cml-publish low_std_errors.png --md >> report.md
          
          cml-send-comment report.md
